# Generated by Django 3.2.7 on 2021-11-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_price'),
        ('orders', '0003_auto_20211116_1907'),
    ]

    operations = [
    ]
